export const GREATER_THAN = 'greater_than'
export const LESS_THAN = 'less_than'
export const GREATER_THAN_OR_EQUAL_TO = 'greater_than_or_equal_to'
export const LESS_THAN_OR_EQUAL_TO = 'less_than_or_equal_to'
export const EQUAL_TO = 'equal_to'
export const NOT_EQUAL_TO = 'not_equal_to'
